// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attendances": {
            "get": {
                "description": "Get attendances with optional filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendances"
                ],
                "summary": "Get attendances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Attendance"
                            }
                        }
                    }
                }
            }
        },
        "/attendances/clock-in": {
            "post": {
                "description": "Create an attendance record for the logged in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendances"
                ],
                "summary": "Clock-in attendances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Attendance"
                        }
                    }
                }
            }
        },
        "/attendances/clock-out": {
            "post": {
                "description": "Update check-out for the logged in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendances"
                ],
                "summary": "Clock-out attendances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Attendance"
                        }
                    }
                }
            }
        },
        "/attendances/today": {
            "get": {
                "description": "Get all attendance records for today",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendances"
                ],
                "summary": "Get today's attendances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Attendance"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Logs in a user using username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logs out a user and revokes their refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout user",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "name": "refresh_token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Get a new access token using a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "name": "refresh_token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/cash-advances": {
            "get": {
                "description": "Get a list of cash advance requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cash-advances"
                ],
                "summary": "Get cash advances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.CashAdvance"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Request a new cash advance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cash-advances"
                ],
                "summary": "Request cash advance",
                "parameters": [
                    {
                        "description": "Cash advance request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.CashAdvanceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.CashAdvance"
                        }
                    }
                }
            }
        },
        "/cash-advances/payment": {
            "post": {
                "description": "Record a payment toward a cash advance (debt)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cash-advances"
                ],
                "summary": "Add cash advance payment",
                "parameters": [
                    {
                        "description": "Payment details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.CashAdvancePayment"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/cash-advances/{id}/status": {
            "put": {
                "description": "Approve or reject a cash advance request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cash-advances"
                ],
                "summary": "Update cash advance status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Cash Advance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.CashAdvanceStatusUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/employees": {
            "get": {
                "description": "Get a list of all employees",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Get all employees",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Employee"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Create an employee",
                "parameters": [
                    {
                        "description": "Employee object",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Employee"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Employee"
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "get": {
                "description": "Get an employee by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Get a single employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Employee"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an employee profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Update an employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Employee object",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Employee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Employee"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an employee profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Delete an employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check the server health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health Check API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/holidays": {
            "get": {
                "description": "Get a list of holidays",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "Get holidays",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Holiday"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new holiday",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "Create holiday",
                "parameters": [
                    {
                        "description": "Holiday request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.HolidayRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Holiday"
                        }
                    }
                }
            }
        },
        "/leaves": {
            "get": {
                "description": "Get a list of leave requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leaves"
                ],
                "summary": "Get leaves",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type filter (cuti/sakit)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Leave"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Request a new leave or sick day",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leaves"
                ],
                "summary": "Request Leave",
                "parameters": [
                    {
                        "description": "Leave request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.LeaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Leave"
                        }
                    }
                }
            }
        },
        "/leaves/{id}/status": {
            "put": {
                "description": "Approve or reject a leave request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leaves"
                ],
                "summary": "Update leave status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Leave ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Leave status override",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.LeaveStatusUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/overtimes": {
            "get": {
                "description": "Get a list of overtime requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "overtimes"
                ],
                "summary": "Get overtimes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Overtime"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Request a new overtime",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "overtimes"
                ],
                "summary": "Request overtime",
                "parameters": [
                    {
                        "description": "Overtime request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.OvertimeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Overtime"
                        }
                    }
                }
            }
        },
        "/overtimes/{id}/status": {
            "put": {
                "description": "Approve or reject an overtime request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "overtimes"
                ],
                "summary": "Update overtime status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Overtime ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.OvertimeStatusUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/reports/monthly-summary": {
            "get": {
                "description": "Get a summary of attendances, overtimes, leaves, and debts for a specific month",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get monthly summary report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Month (1-12), defaults to current",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Year (YYYY), defaults to current",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.MonthlySummaryReport"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_azmeela_sispeg-api_internal_domain.Attendance": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "time_in": {
                    "type": "string"
                },
                "time_out": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_azmeela_sispeg-api_internal_domain.Employee"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.CashAdvance": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "purpose": {
                    "type": "string"
                },
                "status": {
                    "description": "0: created, 1: approved, 2: disapproved",
                    "type": "integer"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.CashAdvancePayment": {
            "type": "object",
            "required": [
                "amount",
                "date",
                "employee_id"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.CashAdvanceRequest": {
            "type": "object",
            "required": [
                "amount",
                "date",
                "purpose"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.CashAdvanceStatusUpdate": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.Employee": {
            "type": "object",
            "properties": {
                "base_salary": {
                    "type": "integer"
                },
                "bio": {
                    "type": "string"
                },
                "contract_end": {
                    "type": "string"
                },
                "contract_start": {
                    "type": "string"
                },
                "cv": {
                    "type": "string"
                },
                "date_sign": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "type_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.Holiday": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_repeated": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.HolidayRequest": {
            "type": "object",
            "required": [
                "date",
                "name"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "is_repeated": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.Leave": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                },
                "grouping": {
                    "type": "integer"
                },
                "id": {
                    "description": "Or id_sakit",
                    "type": "integer"
                },
                "status": {
                    "description": "0: created, 1: approved, 2: disapproved",
                    "type": "integer"
                },
                "type": {
                    "description": "\"cuti\" or \"sakit\" for API level abstraction",
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.LeaveRequest": {
            "type": "object",
            "required": [
                "description",
                "end_date",
                "start_date",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "cuti",
                        "sakit"
                    ]
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.LeaveStatusUpdate": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "status": {
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "cuti",
                        "sakit"
                    ]
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.MonthlySummaryReport": {
            "type": "object",
            "properties": {
                "total_attendances": {
                    "type": "integer"
                },
                "total_debts": {
                    "type": "integer"
                },
                "total_leaves": {
                    "type": "integer"
                },
                "total_overtimes": {
                    "type": "integer"
                },
                "total_sick_days": {
                    "type": "integer"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.Overtime": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "description": "0: created, 1: approved, 2: disapproved",
                    "type": "integer"
                },
                "time_in": {
                    "type": "string"
                },
                "time_out": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.OvertimeRequest": {
            "type": "object",
            "required": [
                "date",
                "description",
                "time_in",
                "time_out"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "time_in": {
                    "type": "string"
                },
                "time_out": {
                    "type": "string"
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.OvertimeStatusUpdate": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                }
            }
        },
        "github_com_azmeela_sispeg-api_internal_domain.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Sispeg API",
	Description:      "This is the core API for Sispeg Project in Azmeela",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
